# Generated by Django 4.1.2 on 2022-10-25 23:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('year', models.IntegerField()),
                ('type', models.CharField(max_length=100)),
                ('nickname', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('distance', models.IntegerField(verbose_name='distance (miles)')),
                ('altitude', models.IntegerField(verbose_name='altitude gain')),
                ('rwgps_url', models.CharField(max_length=250, verbose_name='Ride with GPS link')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('R', 'Road'), ('M', 'Mountain')], default='R', max_length=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.route')),
            ],
            options={
                'ordering': ['date'],
            },
        ),
    ]
