# Generated by Django 4.1.2 on 2022-10-26 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nutrition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('calories', models.CharField(max_length=100, verbose_name='Calories per serving/bottle')),
                ('type', models.CharField(choices=[('W', 'Water'), ('G', 'Gel'), ('B', 'Bar'), ('C', 'Chews'), ('S', 'Sports drink')], default='W', max_length=1)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
