# Generated by Django 4.1.2 on 2022-10-24 19:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bike',
            name='brand',
            field=models.CharField(default='Bike', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='description',
            field=models.TextField(default='Bike', max_length=250),
        ),
        migrations.AddField(
            model_name='bike',
            name='model',
            field=models.CharField(default='Bike', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='nickname',
            field=models.CharField(default='Bike', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='type',
            field=models.CharField(default='Bike', max_length=100),
        ),
        migrations.AddField(
            model_name='bike',
            name='year',
            field=models.IntegerField(default=2022),
        ),
    ]
