# Generated by Django 4.1.2 on 2022-10-25 19:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_bike_brand_bike_description_bike_model_bike_nickname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bike',
            name='brand',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='description',
            field=models.TextField(max_length=250),
        ),
        migrations.AlterField(
            model_name='bike',
            name='model',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='nickname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='bike',
            name='year',
            field=models.IntegerField(),
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('type', models.CharField(choices=[('R', 'Road'), ('M', 'Mountain')], default='R', max_length=1)),
                ('bike', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.bike')),
            ],
        ),
    ]
