# Generated by Django 4.1.2 on 2022-10-26 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0002_nutrition'),
    ]

    operations = [
        migrations.AddField(
            model_name='nutrition',
            name='ride',
            field=models.ManyToManyField(to='main_app.ride'),
        ),
    ]
