# Generated by Django 4.1.2 on 2022-10-26 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_nutrition_ride'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='ride',
        ),
        migrations.AddField(
            model_name='ride',
            name='nutrition',
            field=models.ManyToManyField(to='main_app.nutrition'),
        ),
    ]
