# Generated by Django 4.1.2 on 2022-10-26 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_remove_nutrition_ride_ride_nutrition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nutrition',
            name='calories',
            field=models.IntegerField(verbose_name='Calories per serving/bottle'),
        ),
    ]
