# Generated by Django 4.1.2 on 2022-10-26 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0005_alter_nutrition_calories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='nutrition',
        ),
    ]
