# Generated by Django 4.1.2 on 2022-10-27 00:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0006_remove_ride_nutrition'),
    ]

    operations = [
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=30)),
                ('nutrient', models.ManyToManyField(to='main_app.nutrition')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ride')),
            ],
        ),
    ]
