# Generated by Django 4.1.2 on 2022-10-28 16:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0008_ride_nutrition_delete_nutritionplan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='nutrition',
        ),
        migrations.CreateModel(
            name='NutritionPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.CharField(max_length=50)),
                ('nutrition', models.ManyToManyField(to='main_app.nutrition')),
                ('ride', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main_app.ride')),
            ],
        ),
    ]
