# Generated by Django 4.1.2 on 2022-10-29 03:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0009_remove_ride_nutrition_nutritionplan'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nutritionplan',
            options={'ordering': ['time']},
        ),
    ]
