# Generated by Django 4.1.2 on 2022-10-29 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0010_alter_nutritionplan_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nutrition',
            name='calories',
        ),
        migrations.AddField(
            model_name='nutrition',
            name='carbs',
            field=models.IntegerField(default=0, verbose_name='Grams of carbs per serving/bottle'),
            preserve_default=False,
        ),
    ]
