# Generated by Django 4.1.2 on 2022-10-29 04:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0011_remove_nutrition_calories_nutrition_carbs'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='est_time',
            field=models.IntegerField(default=2, verbose_name='Estimated time (in hrs)'),
            preserve_default=False,
        ),
    ]
